/**
 * AI Summary Formatter - Week-2B
 *
 * Generates "AI Powered Match Summary" messages for Telegram channels
 * Based on the scoring engine's output (NO picks modification)
 *
 * Features:
 * - TR/EN locale support
 * - Emoji minimal / no emoji variants
 * - Data-driven, neutral tone
 * - Guardrails: LLM NEVER modifies picks
 * - Template-based generation (no actual LLM calls yet)
 *
 * Format:
 * - Header: "GoalGPT AI Stats Summary"
 * - 1 paragraph overview (data-driven, neutral)
 * - Key angles (4-6 bullets)
 * - Bet ideas (2-4 lines - ONLY for canPublish=true markets)
 * - Disclaimer footer
 *
 * @author GoalGPT Team
 * @version 1.0.0
 */

import type { ScoringResult } from '../scoring/marketScorer.service';
import type { PublishEligibilityResult } from '../scoring/publishEligibility';

// ============================================================================
// TYPES
// ============================================================================

export type Locale = 'tr' | 'en';
export type EmojiStyle = 'minimal' | 'none';

export interface MatchSummaryInput {
  homeTeam: string;
  awayTeam: string;
  league: string;
  matchTime: string;
  predictions: {
    marketId: string;
    displayName: string;
    scoringResult: ScoringResult;
    publishEligibility: PublishEligibilityResult;
  }[];
}

export interface SummaryOptions {
  locale?: Locale;
  emojiStyle?: EmojiStyle;
}

export interface FormattedSummary {
  header: string;
  overview: string;
  keyAngles: string[];
  betIdeas: string[];
  footer: string;
  fullText: string;
}

// ============================================================================
// DATA INTEGRITY THRESHOLDS (Week-2B Hardening)
// ============================================================================

/**
 * xG (Expected Goals) thresholds for text labels
 * Based on statistical analysis of goal-scoring patterns
 */
const XG_THRESHOLDS = {
  HIGH: 2.8,    // >= 2.8 xG = High scoring potential
  MEDIUM: 2.0,  // >= 2.0 xG = Medium scoring potential
  // < 2.0 = Low scoring potential
} as const;

/**
 * Edge (value) thresholds for bet ideas
 * Edge = probability - implied_probability (from odds)
 */
const EDGE_THRESHOLDS = {
  SIGNIFICANT: 0.05,  // >= 5% edge = Significant value
  MINIMAL: 0.02,      // >= 2% edge = Minimal value
} as const;

// ============================================================================
// LOCALE STRINGS
// ============================================================================

const LOCALE_STRINGS = {
  tr: {
    header: '🤖 GoalGPT AI İstatistik Özeti',
    headerNoEmoji: 'GoalGPT AI İstatistik Özeti',
    keyAnglesTitle: '📊 Öne Çıkan Noktalar:',
    keyAnglesTitleNoEmoji: 'Öne Çıkan Noktalar:',
    betIdeasTitle: '💡 Bahis Fikirleri:',
    betIdeasTitleNoEmoji: 'Bahis Fikirleri:',
    // HARDENING: Single-line disclaimer for Telegram readability
    disclaimer:
      '⚠️ GoalGPT AI tarafından FootyStats verisiyle oluşturulmuştur. Kesin doğruluk garantisi verilmez.',
    disclaimerNoEmoji:
      '* GoalGPT AI tarafından FootyStats verisiyle oluşturulmuştur. Kesin doğruluk garantisi verilmez.',
    confidence: 'Güven',
    probability: 'Olasılık',
    edge: 'Değer',
    match: 'Maç',
    league: 'Lig',
    time: 'Saat',
    // Threshold labels
    xgHigh: 'Yüksek',
    xgMedium: 'Orta',
    xgLow: 'Düşük',
  },
  en: {
    header: '🤖 GoalGPT AI Stats Summary',
    headerNoEmoji: 'GoalGPT AI Stats Summary',
    keyAnglesTitle: '📊 Key Angles:',
    keyAnglesTitleNoEmoji: 'Key Angles:',
    betIdeasTitle: '💡 Bet Ideas:',
    betIdeasTitleNoEmoji: 'Bet Ideas:',
    // HARDENING: Single-line disclaimer for Telegram readability
    disclaimer:
      '⚠️ Generated by GoalGPT AI using FootyStats data. No guarantee of exact correctness.',
    disclaimerNoEmoji:
      '* Generated by GoalGPT AI using FootyStats data. No guarantee of exact correctness.',
    confidence: 'Confidence',
    probability: 'Probability',
    edge: 'Edge',
    match: 'Match',
    league: 'League',
    time: 'Time',
    // Threshold labels
    xgHigh: 'High',
    xgMedium: 'Medium',
    xgLow: 'Low',
  },
};

// ============================================================================
// FORMATTER
// ============================================================================

class AISummaryFormatter {
  /**
   * Generate match summary from scoring results
   *
   * @param input - Match and prediction data
   * @param options - Formatting options
   * @returns Formatted summary
   */
  formatMatchSummary(input: MatchSummaryInput, options: SummaryOptions = {}): FormattedSummary {
    const locale = options.locale || 'tr';
    const emojiStyle = options.emojiStyle || 'minimal';
    const strings = LOCALE_STRINGS[locale];

    // Header
    const header = emojiStyle === 'none' ? strings.headerNoEmoji : strings.header;

    // Overview paragraph
    const overview = this.generateOverview(input, locale);

    // Key angles (4-6 bullets from scoring metadata)
    const keyAngles = this.generateKeyAngles(input, locale, emojiStyle);

    // Bet ideas (ONLY from canPublish=true markets)
    const betIdeas = this.generateBetIdeas(input, locale);

    // Footer disclaimer
    const footer = emojiStyle === 'none' ? strings.disclaimerNoEmoji : strings.disclaimer;

    // Combine into full text
    const fullText = this.assembleFullText(header, overview, keyAngles, betIdeas, footer, strings, emojiStyle);

    return {
      header,
      overview,
      keyAngles,
      betIdeas,
      footer,
      fullText,
    };
  }

  /**
   * Generate overview paragraph
   * Data-driven, neutral tone
   */
  private generateOverview(input: MatchSummaryInput, locale: Locale): string {
    const { homeTeam, awayTeam, predictions } = input;

    // Count publishable markets
    const publishableCount = predictions.filter((p) => p.publishEligibility.canPublish).length;

    // Calculate average confidence for publishable predictions
    const publishablePreds = predictions.filter((p) => p.publishEligibility.canPublish);
    const avgConfidence =
      publishablePreds.length > 0
        ? Math.round(
            publishablePreds.reduce((sum, p) => sum + p.scoringResult.confidence, 0) / publishablePreds.length
          )
        : 0;

    // Get highest probability market
    const topMarket = publishablePreds.sort((a, b) => b.scoringResult.probability - a.scoringResult.probability)[0];

    if (locale === 'tr') {
      if (publishableCount === 0) {
        return `${homeTeam} - ${awayTeam} maçı için ${predictions.length} market analiz edildi. Yüksek güvenli tahmin bulunamadı.`;
      }

      return (
        `${homeTeam} - ${awayTeam} maçı için ${predictions.length} market analiz edildi. ` +
        `${publishableCount} market yayına uygun bulundu (ortalama güven: ${avgConfidence}%). ` +
        `En yüksek olasılık: ${topMarket.displayName} %${(topMarket.scoringResult.probability * 100).toFixed(1)}.`
      );
    } else {
      if (publishableCount === 0) {
        return `${homeTeam} vs ${awayTeam}: ${predictions.length} markets analyzed. No high-confidence predictions found.`;
      }

      return (
        `${homeTeam} vs ${awayTeam}: ${predictions.length} markets analyzed. ` +
        `${publishableCount} markets eligible for publish (avg confidence: ${avgConfidence}%). ` +
        `Highest probability: ${topMarket.displayName} ${(topMarket.scoringResult.probability * 100).toFixed(1)}%.`
      );
    }
  }

  /**
   * Generate key angles from metadata
   * 4-6 bullets highlighting data insights
   * HARDENING: Uses threshold constants for data-driven labels
   */
  private generateKeyAngles(input: MatchSummaryInput, locale: Locale, emojiStyle: EmojiStyle): string[] {
    const angles: string[] = [];
    const { predictions } = input;
    const strings = LOCALE_STRINGS[locale];

    // Extract metadata from O25/O35 predictions (lambda values)
    const o25 = predictions.find((p) => p.marketId === 'O25');
    const btts = predictions.find((p) => p.marketId === 'BTTS');

    if (o25 && o25.scoringResult.metadata.lambda_total) {
      const lambda = o25.scoringResult.metadata.lambda_total;
      const bullet = emojiStyle === 'none' ? '-' : '⚽';

      // HARDENING: Use threshold constants instead of hardcoded values
      const levelLabel = lambda >= XG_THRESHOLDS.HIGH
        ? strings.xgHigh
        : lambda >= XG_THRESHOLDS.MEDIUM
        ? strings.xgMedium
        : strings.xgLow;

      angles.push(
        locale === 'tr'
          ? `${bullet} Beklenen gol (xG): ${lambda.toFixed(2)} - ${levelLabel} seviye`
          : `${bullet} Expected goals (xG): ${lambda.toFixed(2)} - ${levelLabel} level`
      );
    }

    if (btts && btts.scoringResult.metadata.home_scoring_prob && btts.scoringResult.metadata.away_scoring_prob) {
      const homeProb = (btts.scoringResult.metadata.home_scoring_prob * 100).toFixed(0);
      const awayProb = (btts.scoringResult.metadata.away_scoring_prob * 100).toFixed(0);
      const bullet = emojiStyle === 'none' ? '-' : '🎯';
      angles.push(
        locale === 'tr'
          ? `${bullet} Gol atma olasılığı: Ev %${homeProb} / Deplasman %${awayProb}`
          : `${bullet} Scoring probability: Home ${homeProb}% / Away ${awayProb}%`
      );
    }

    // Add confidence distribution
    const highConf = predictions.filter((p) => p.scoringResult.confidence >= 70).length;
    if (highConf > 0) {
      const bullet = emojiStyle === 'none' ? '-' : '📈';
      angles.push(
        locale === 'tr'
          ? `${bullet} ${highConf} market yüksek güven seviyesinde (≥70%)`
          : `${bullet} ${highConf} markets with high confidence (≥70%)`
      );
    }

    // Add value detection (positive edge)
    const valueMarkets = predictions.filter(
      (p) => p.scoringResult.edge !== null && p.scoringResult.edge > 0.05
    ).length;
    if (valueMarkets > 0) {
      const bullet = emojiStyle === 'none' ? '-' : '💎';
      angles.push(
        locale === 'tr'
          ? `${bullet} ${valueMarkets} markette değer fırsatı tespit edildi`
          : `${bullet} ${valueMarkets} markets with value opportunity detected`
      );
    }

    // Add risk flag summary
    const cleanPredictions = predictions.filter((p) => p.scoringResult.risk_flags.length === 0).length;
    if (cleanPredictions > 0) {
      const bullet = emojiStyle === 'none' ? '-' : '✅';
      angles.push(
        locale === 'tr'
          ? `${bullet} ${cleanPredictions} market tam veri seti ile analiz edildi`
          : `${bullet} ${cleanPredictions} markets analyzed with complete data`
      );
    }

    return angles.slice(0, 6); // Max 6 bullets
  }

  /**
   * Generate bet ideas (ONLY from canPublish=true markets)
   * GUARDRAIL: Uses ONLY scorer picks, never modifies them
   * HARDENING: Edge calculation is explicit (edge = probability - implied_probability)
   */
  private generateBetIdeas(input: MatchSummaryInput, locale: Locale): string[] {
    const ideas: string[] = [];
    const publishable = input.predictions.filter((p) => p.publishEligibility.canPublish);

    if (publishable.length === 0) {
      return locale === 'tr'
        ? ['Yayına uygun yüksek güvenli tahmin bulunamadı.']
        : ['No high-confidence predictions eligible for publish.'];
    }

    // Sort by confidence
    const sorted = publishable.sort((a, b) => b.scoringResult.confidence - a.scoringResult.confidence);

    // Top 2-4 markets
    for (const pred of sorted.slice(0, 4)) {
      const { displayName, scoringResult } = pred;
      const { confidence, probability, edge } = scoringResult;

      // HARDENING: Explicit edge display with threshold-based formatting
      // Edge = probability - implied_probability (from odds)
      let edgeText = '';
      if (edge !== null && edge > 0) {
        const edgePercentage = (edge * 100).toFixed(1);
        if (locale === 'tr') {
          edgeText = edge >= EDGE_THRESHOLDS.SIGNIFICANT
            ? ` | Değer: +${edgePercentage}% (yüksek)`
            : ` | Değer: +${edgePercentage}%`;
        } else {
          edgeText = edge >= EDGE_THRESHOLDS.SIGNIFICANT
            ? ` | Edge: +${edgePercentage}% (high)`
            : ` | Edge: +${edgePercentage}%`;
        }
      }

      if (locale === 'tr') {
        ideas.push(
          `${displayName}: %${(probability * 100).toFixed(1)} olasılık (Güven: ${confidence}/100)${edgeText}`
        );
      } else {
        ideas.push(
          `${displayName}: ${(probability * 100).toFixed(1)}% probability (Confidence: ${confidence}/100)${edgeText}`
        );
      }
    }

    return ideas;
  }

  /**
   * Assemble full text message
   */
  private assembleFullText(
    header: string,
    overview: string,
    keyAngles: string[],
    betIdeas: string[],
    footer: string,
    strings: any,
    emojiStyle: EmojiStyle
  ): string {
    const sections: string[] = [];

    // Header
    sections.push(header);
    sections.push(''); // Blank line

    // Overview
    sections.push(overview);
    sections.push(''); // Blank line

    // Key Angles
    if (keyAngles.length > 0) {
      sections.push(emojiStyle === 'none' ? strings.keyAnglesTitleNoEmoji : strings.keyAnglesTitle);
      keyAngles.forEach((angle) => sections.push(angle));
      sections.push(''); // Blank line
    }

    // Bet Ideas
    if (betIdeas.length > 0) {
      sections.push(emojiStyle === 'none' ? strings.betIdeasTitleNoEmoji : strings.betIdeasTitle);
      betIdeas.forEach((idea) => sections.push(idea));
      sections.push(''); // Blank line
    }

    // Footer
    sections.push(footer);

    return sections.join('\n');
  }

  /**
   * Format a single market prediction (for list publishing)
   * HARDENING: Consistent edge calculation display
   *
   * @param marketDisplayName - Market display name
   * @param scoringResult - Scoring result
   * @param locale - Locale
   * @returns Formatted prediction line
   */
  formatPrediction(marketDisplayName: string, scoringResult: ScoringResult, locale: Locale = 'tr'): string {
    const strings = LOCALE_STRINGS[locale];
    const { confidence, probability, edge } = scoringResult;

    const probText = `${(probability * 100).toFixed(1)}%`;
    const confText = `${confidence}/100`;

    // HARDENING: Consistent edge display (edge = probability - implied_probability)
    let edgeText = '';
    if (edge !== null && edge > 0) {
      const edgePercentage = (edge * 100).toFixed(1);
      edgeText = ` | ${strings.edge}: +${edgePercentage}%`;
    }

    if (locale === 'tr') {
      return `${marketDisplayName}: ${probText} (${strings.confidence}: ${confText}${edgeText})`;
    } else {
      return `${marketDisplayName}: ${probText} (${strings.confidence}: ${confText}${edgeText})`;
    }
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export const aiSummaryFormatter = new AISummaryFormatter();
export { AISummaryFormatter };
